# Generated by Django 3.2.25 on 2025-08-26 21:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date_earned'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['deadline'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_created'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.TextField(blank=True, help_text='(Optional) What was the outcome or impact?'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_solved',
            field=models.TextField(blank=True, help_text='(Optional) What problem did this project solve?'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', help_text='Current status of the project.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='tools_used',
            field=models.TextField(blank=True, help_text='(Optional) Which tools/technologies did you use?'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_earned',
            field=models.DateField(help_text='Date when the certificate was earned.'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_upload',
            field=models.FileField(blank=True, help_text='Optional proof file (PDF/image).', null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp']), users.models.validate_file_size_5mb]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(help_text='Organization/platform that issued the certificate.', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(help_text='Certificate title.', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(help_text='Owner of this certificate.', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this goal was created.'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(help_text='Deadline for completing the target.'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_projects',
            field=models.IntegerField(help_text='How many projects the user aims to complete.'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(help_text='Owner of this goal.', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='certificate',
            field=models.ForeignKey(blank=True, help_text='Optionally link this project to a certificate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.certificate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='When this project was created.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='What you built, how, tools used, and impact.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Project title.', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(help_text='Owner of this project.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
