# Generated by Django 3.2.25 on 2025-08-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250826_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges_short',
            field=models.TextField(blank=True, help_text='Key challenges faced (short).', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='duration_text',
            field=models.CharField(blank=True, help_text="Rough duration (e.g., '2 weeks', 'a weekend').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome_short',
            field=models.TextField(blank=True, help_text='Concise outcome/impact.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_goal',
            field=models.CharField(blank=True, choices=[('practice_skill', 'Practice a skill'), ('deliver_feature', 'Deliver a feature'), ('build_demo', 'Build a demo'), ('solve_problem', 'Solve a problem')], help_text='The main intent behind this project.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skills_to_improve',
            field=models.TextField(blank=True, help_text='What to practice more next time.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skills_used',
            field=models.TextField(blank=True, help_text='Skills/tools used (CSV or short text).', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='work_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('team', 'Team')], help_text='Was this an individual or team project?', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='What you built, how, tools used, and impact.'),
        ),
    ]
