# Generated by Django 3.2.25 on 2025-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250827_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='impact',
        ),
        migrations.AlterField(
            model_name='project',
            name='outcome_short',
            field=models.TextField(blank=True, help_text='(Optional) What was the outcome or impact?', null=True),
        ),
    ]
