# Generated by Django 3.2.25 on 2025-08-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20250827_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(help_text='Issuing organization/platform.', max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(help_text='Target deadline.'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_projects',
            field=models.IntegerField(help_text='Number of projects to complete.'),
        ),
    ]
