# Generated by Django 4.2.16 on 2025-08-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20250828_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_steps',
            field=models.PositiveIntegerField(default=0, help_text='Completed checklist steps (optional).'),
        ),
        migrations.AddField(
            model_name='goal',
            name='total_steps',
            field=models.PositiveIntegerField(default=0, help_text='Total checklist steps (optional).'),
        ),
    ]
