# Generated by Django 4.2.16 on 2025-08-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_goal_completed_steps_goal_total_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(default='Untitled goal', help_text='Short label for this goal.', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GoalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description of the step.', max_length=255)),
                ('is_done', models.BooleanField(default=False, help_text='Mark when this step is completed.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Optional order/index among steps.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.')),
                ('goal', models.ForeignKey(help_text='Parent goal for this step.', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='users.goal')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
