# Generated by Django 4.2.16 on 2025-08-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_goal_title_goalstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goalstep',
            name='is_done',
            field=models.BooleanField(default=False, help_text='Checked/done?'),
        ),
        migrations.AlterField(
            model_name='goalstep',
            name='order',
            field=models.IntegerField(default=0, help_text='Optional manual ordering.'),
        ),
        migrations.AlterField(
            model_name='goalstep',
            name='title',
            field=models.CharField(help_text='Step title/label.', max_length=255),
        ),
    ]
