# Generated by Django 4.2.16 on 2025-09-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_goalstep_created_at_alter_goalstep_is_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='outcome_short',
        ),
        migrations.AddField(
            model_name='project',
            name='duration_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Numeric amount for the duration (e.g., 2).', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], help_text='Unit for the duration (e.g., weeks).', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration_text',
            field=models.CharField(blank=True, help_text='DEPRECATED: auto-filled from structured duration; legacy display.', max_length=100, null=True),
        ),
    ]
