# Generated by Django 4.2.16 on 2025-09-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_project_outcome_short_project_duration_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional end date.', null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Optional start date.', null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenges_short',
            field=models.TextField(blank=True, help_text='Key challenges faced (short).', null=True, verbose_name='Challenges encountered'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Numeric amount for the duration (e.g., 2). Used when dates are not provided.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration_text',
            field=models.CharField(blank=True, help_text='Auto-filled from start/end dates (preferred) or from structured duration.', max_length=100, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], help_text='Unit for the duration (e.g., weeks). Used when dates are not provided.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills_used',
            field=models.TextField(blank=True, help_text='Skills practiced (CSV or short text).', null=True, verbose_name='Skills practiced'),
        ),
    ]
