# Generated by Django 4.2.16 on 2025-09-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_project_end_date_project_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration_unit',
        ),
        migrations.AlterField(
            model_name='project',
            name='duration_text',
            field=models.CharField(blank=True, help_text='Auto-filled from start/end dates.', max_length=100, null=True, verbose_name='Duration'),
        ),
    ]
