# Generated by Django 4.2.16 on 2025-09-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_project_duration_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='completed_steps',
            field=models.PositiveIntegerField(default=0, help_text='Completed checklist steps (optional).', verbose_name='Accomplished steps'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_projects',
            field=models.IntegerField(help_text='Number of projects to complete (must be ≥ 1).', verbose_name='Target number of projects to build'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='total_steps',
            field=models.PositiveIntegerField(default=0, help_text='Total checklist steps (optional).', verbose_name='Overall required steps'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Required when status is Completed; must be after Start date.', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Required. Planned: today or future; In progress: today or past; Completed: yesterday or earlier.', null=True, verbose_name='Start date'),
        ),
    ]
