# Generated by Django 4.2.16 on 2025-09-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_goal_completed_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_projects',
            field=models.PositiveIntegerField(default=0, help_text="Number of projects you've actually completed toward this goal", verbose_name='Accomplished projects'),
        ),
    ]
