# Generated by Django 4.2.16 on 2025-09-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_goal_completed_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='completed_projects',
            field=models.PositiveIntegerField(default=0, help_text="Number of projects you've actually completed toward this goal (0..target_projects).", verbose_name='Accomplished projects'),
        ),
    ]
