name: Backend Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (verbose)
        env:
          # Safe defaults for CI; override with real envs in a prod workflow if needed
          DJANGO_DEBUG: "False"
          DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
          CORS_ALLOW_ALL_ORIGINS: "False"
        run: |
          python manage.py test -v 2
