# Generated by Django 4.2.16 on 2025-09-03 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='discount_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0–100; only used when type=discount.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ends_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='platform',
            field=models.CharField(db_index=True, help_text='e.g. Udemy, Coursera, 365 Data Science', max_length=80),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price_current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='starts_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of strings, e.g. ['AI','Beginner']"),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text='Human title shown to users.', max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('discount', 'Discount')], db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='url',
            field=models.URLField(help_text='External page to visit/enroll.', max_length=500),
        ),
        migrations.AlterField(
            model_name='fact',
            name='active',
            field=models.BooleanField(default=True, help_text='If false, excluded from the random picker.'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='source',
            field=models.CharField(blank=True, help_text='Short label for the source (optional).', max_length=200),
        ),
        migrations.AlterField(
            model_name='fact',
            name='source_url',
            field=models.URLField(blank=True, help_text='Clickable URL for the source (optional).', max_length=500),
        ),
        migrations.AlterField(
            model_name='fact',
            name='text',
            field=models.TextField(help_text='The fact body shown on the Home page.'),
        ),
    ]
