# This will:
# - Run on every push + PR
# - Install deps from requirements.txt
# - Run your Django tests with verbose output (-v 2) so you get the full test names.


name: Django Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]  # Django 3.2 LTS supports up to 3.10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show Python version
        run: python --version

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests (verbose)
        env:
          # Safe defaults for CI; override with real envs in a prod workflow if needed
          DJANGO_SECRET_KEY: ci-secret
          DJANGO_DEBUG: "False"
          DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
          CORS_ALLOW_ALL_ORIGINS: "False"
        run: |
          python manage.py test -v 2

